services:
  postgres:
    image: postgres:17-alpine
    container_name: ecommerce-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - ecommerce-network


  postgres-test:
    image: postgres:17-alpine
    container_name: ecommerce-postgres-test
    restart: unless-stopped

    environment:
      POSTGRES_DB: ecommerce_test_db
      POSTGRES_USER: ecommerce_test_user
      POSTGRES_PASSWORD: ecommerce_test_password

    ports:
      - "5433:5432"

    tmpfs:
      - /var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ecommerce_test_user -d ecommerce_test_db"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

    networks:
      - ecommerce-network


volumes:
  postgres_data:
    name: ecommerce-postgres-data


networks:
  ecommerce-network:
    name: ecommerce-network
    driver: bridge